version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tiflux-mcp-stack"
s3_prefix = "tiflux-mcp"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
resolve_s3 = true
